---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: egress-gateway
  namespace: istio-egress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: egress-gateway-istio
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80