---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: egress-gateway
  namespace: istio-egress
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      istio.io/gateway-name: egress-gateway