operators-installer:

  operators:
    - channel: stable
      installPlanApproval: "Manual"
      name: local-storage-operator
      sourceNamespace: openshift-marketplace
      source: redhat-operators
      csv: local-storage-operator.v4.17.0-202501220934
      namespace: openshift-local-storage
      automaticIntermediateManualUpgrades: true

  operatorGroups:
  - name: openshift-local-storage
    createNamespace: true
    targetOwnNamespace: false
