---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tenant-gitops-argocd-application-controller-allow-list
subjects:
  - kind: ServiceAccount
    name: tenant-gitops-argocd-application-controller
    namespace: tenant-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: safer-cluster-admin
