---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: auto-provisioned-namespace
spec:
  labelSelector:
    matchLabels:
      gitops.ticq.dev/user-sandbox: "true"
  templates:
  - excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas
    objectTemplate: |
      apiVersion: v1
      kind: LimitRange
      metadata:
        name: limit-range
        namespace: {{`{{ .Name }}`}}
      spec:
        limits:
        - type: Container
          default:
            cpu: 300m
            ephemeral-storage: 1Gi
            memory: 200Mi
          defaultRequest:
            cpu: 50m
            ephemeral-storage: 100Mi
            memory: 100Mi
          max:
            cpu: "1"
            ephemeral-storage: 5Gi
            memory: 1Gi
          min:
            cpu: 10m
            memory: 10Mi
        - type: PersistentVolumeClaim
          max:
            storage: 1Gi
          min:
            storage: 1Gi

  - excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas
    objectTemplate: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: test
        namespace: {{`{{ .Name }}`}}
      data:
        foo: bar
