---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: auto-provisioned-namespace
spec:
  labelSelector:
    matchLabels:
      user-auto-provisioned: "true"
  templates:
  - excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas
    objectTemplate: |
      apiVersion: v1
      kind: ResourceQuota
      metadata:
        name: small-size
        namespace: {{`{{ .Name }}`}}
      spec:
        hard:
          requests.cpu: "4"
          requests.memory: "2Gi"
  - excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas
    objectTemplate: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: test
        namespace: {{`{{ .Name }}`}}
      data:
        foo: bar
