# all resources tenants are able to edit/use
# copied from OpenShift edit role
# but does not contain aggregation to make sure
# we don't by accident add rights to tenants
tenantResources:
  - verbs:
      - "*"
    apiGroups:
      - ''
    resources:
      - secrets
      - serviceaccounts
      - pods
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
      - pods/log
      - pods/status
      - configmaps
      - persistentvolumeclaims
      - services
      - services/proxy
      # - pods/eviction # ??
    argoKinds: ["Secret", "ServiceAccount", "Pod", "Service", "ConfigMap", "PersistentVolumeClaim"]
  - verbs:
    - "*"
    apiGroups:
    - gateway.networking.k8s.io
    resources:
    - httproutes
    - tlsroutes
    argoKinds: ["HTTPRoute", "TLSRoute"]
  - verbs:
    - "*"
    apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    - prometheusrules
    - podmonitor
    argoKinds: ["ServiceMonitor", "PrometheusRule", "PodMonitor"]
  - verbs:
      - "*"
    apiGroups:
      - apps
    resources:
      - deployments
      - deployments/rollback
      - deployments/scale
      - deployments/status
      - replicasets
      - replicasets/scale
      - replicasets/status
      - statefulsets
      - statefulsets/scale
      - statefulsets/status
    argoKinds: ["Deployment", "ReplicaSet", "StatefulSet"]
  - verbs:
      - "*"
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
      - horizontalpodautoscalers/status
    argoKinds: ["HorizontalPodAutoscaler"]
  - verbs:
      - "*"
    apiGroups:
      - batch
    resources:
      - cronjobs
      - cronjobs/status
      - jobs
      - jobs/status
    argoKinds: ["CronJob", "Job"]
  - verbs:
      - "*"
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
      - poddisruptionbudgets/status
    argoKinds: ["PodDisruptionBudget"]
  - verbs:
      - "*"
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingresses/status
    argoKinds: ["Ingress"]
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies # network policies is an admin thing
  - verbs:
      - "*"
    apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    argoKinds: ["VolumeSnapshot"]
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - quota.openshift.io
    resources:
      - appliedclusterresourcequotas
  - verbs:
      - "*"
    apiGroups:
      - route.openshift.io
    resources:
      - routes
    argoKinds: ["Route"]
  - verbs:
      - get
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalercheckpoints
      - verticalpodautoscalercontrollers
  - verbs:
      - "*"
    apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
    argoKinds: ["VerticalPodAutoscaler"]
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - bindings
      - events
      - limitranges
      - namespaces/status
      - resourcequotas
      - resourcequotas/status
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
      - events
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
  - verbs:
      - get
    apiGroups:
      - ''
      - project.openshift.io
    resources:
      - projects
