apiVersion: sailoperator.io/v1alpha1
kind: Istio
metadata:
  name: default
spec:
  namespace: istio-system
  values:
    meshConfig:
      accessLogFile: /dev/stdout
    pilot:
      autoscaleMin: 2
      replicaCount: 2
      env:
        # needed for egress TLSRoute functionality
        PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
  updateStrategy:
    type: InPlace
    inactiveRevisionDeletionGracePeriodSeconds: 30
  version: v1.23.0
  profile: openshift

