apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: custom
  namespace: openshift-ingress-operator
spec:
  # defaultCertificate:
  #     name: <custom-ingress-custom-certs> 
  replicas: 1
  domain: ingress.vandulmen.net
  endpointPublishingStrategy:
    type: LoadBalancerService
    # loadBalancer:
    #   scope: Internal