apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: custom
  namespace: openshift-ingress-operator
spec:
  # defaultCertificate:
  #     name: <custom-ingress-custom-certs> 
  routeSelector:
    matchLabels:
      type: custom-domain
  replicas: 1
  domain: ingress.vandulmen.net
  endpointPublishingStrategy:
    nodePort:
      protocol: PROXY
    type: NodePortService