apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: custom
  namespace: openshift-ingress-operator
spec:
  # only TLS 1.3 - CIS benchmark
  tlsSecurityProfile:
    type: Modern

  defaultCertificate:
    name: cloud-ticq-org
  routeSelector:
    matchLabels:
      type: custom-domain
  replicas: 1
  domain: "{{ $.Values.ingressDomain }}"

  # tuning stuff
  # https://www.haproxy.com/blog/multithreading-in-haproxy
  tuningOptions:
    threadCount: 8 # default = 4
    clientTimeout: 10s # 30s = default
    serverFinTimeout: 1s # 1s = default
    serverTimeout: 30s # 30s = default
    clientFinTimeout: 1s # 1s = default
    tlsInspectDelay: 5s # 5s = default

    # specifies how long a tunnel connection, including websockets, 
    # remains open while the tunnel is idle. If unset, the default timeout is 1h.
    tunnelTimeout: 1h # 1h = default

  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""  
    
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved

  # VIP via keepalived operator
  endpointPublishingStrategy: 
    type: NodePortService
    
  # access logging
  logging:
    access:
      destination:
        type: Container