apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: custom
  namespace: openshift-ingress-operator
spec:
  replicas: 1

  # only TLS 1.3
  tlsSecurityProfile:
    type: Modern

  defaultCertificate:
    name: cloud-ticq-org
  routeSelector:
    matchLabels:
      type: custom-domain
  replicas: 1
  domain: "{{ $.Values.ingressDomain }}"

  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""  
    
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      value: reserved
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
      value: reserved

  # VIP via keepalived operator
  endpointPublishingStrategy: 
    type: NodePortService
    
  # access logging
  logging:
    access:
      destination:
        type: Container