apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  replicas: 1 # should be more obviously

  # only TLS 1.3 - CIS benchmark
  tlsSecurityProfile:
    type: Modern

  # enable this for cert-manager provided wildcard cert
  # defaultCertificate:
  #   name: apps-os2-ticq-org

  tuningOptions:
    reloadInterval: 0s
    clientTimeout: 30s # = default
    serverTimeout: 30s # = default
    threadCount: 4 # = default
    maxConnections: 50000 # 50000 = default

  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""  

    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      value: reserved
    - effect: NoExecute
      key: node-role.kubernetes.io/infra
      value: reserved

  # tenant namespaces cant use the default
  namespaceSelector:
    matchExpressions:
    - key: gitops.ticq.dev/tenant
      operator: DoesNotExist
  
  # access logging
  logging:
    access:
      destination:
        type: Container