apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-error-code-pages
  namespace: openshift-config
data:
  error-page-503.http: |
    HTTP/1.0 503 Service Unavailable
    Pragma: no-cache
    Cache-Control: private, max-age=0, no-cache, no-store
    Connection: close
    Content-Type: text/html

    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <style type="text/css">
          body {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            line-height: 1.66666667;
            font-size: 16px;
            color: #333;
            background-color: #fff;
            margin: 2em 1em;
          }
          h1 {
            font-size: 28px;
            font-weight: 400;
          }
          p {
            margin: 0 0 10px;
          }
          .alert.alert-info {
            background-color: #F0F0F0;
            margin-top: 30px;
            padding: 30px;
          }
          .alert p {
            padding-left: 35px;
          }
          ul {
            padding-left: 51px;
            position: relative;
          }
          li {
            font-size: 14px;
            margin-bottom: 1em;
          }
          p.info {
            position: relative;
            font-size: 20px;
          }
          p.info:before, p.info:after {
            content: "";
            left: 0;
            position: absolute;
            top: 0;
          }
          p.info:before {
            background: #0066CC;
            border-radius: 16px;
            color: #fff;
            content: "i";
            font: bold 16px/24px serif;
            height: 24px;
            left: 0px;
            text-align: center;
            top: 4px;
            width: 24px;
          }

          @media (min-width: 768px) {
            body {
              margin: 6em;
            }
          }
        </style>
      </head>
      <body>
        <div>
          <h1>Sorry - We are not available!</h1>
        </div>
      </body>
    </html>
  error-page-404.http: |
    HTTP/1.0 404 Error
    Pragma: no-cache
    Cache-Control: private, max-age=0, no-cache, no-store
    Connection: close
    Content-Type: text/html

    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <style type="text/css">
          body {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            line-height: 1.66666667;
            font-size: 16px;
            color: #333;
            background-color: #fff;
            margin: 2em 1em;
          }
          h1 {
            font-size: 28px;
            font-weight: 400;
          }
          p {
            margin: 0 0 10px;
          }
          .alert.alert-info {
            background-color: #F0F0F0;
            margin-top: 30px;
            padding: 30px;
          }
          .alert p {
            padding-left: 35px;
          }
          ul {
            padding-left: 51px;
            position: relative;
          }
          li {
            font-size: 14px;
            margin-bottom: 1em;
          }
          p.info {
            position: relative;
            font-size: 20px;
          }
          p.info:before, p.info:after {
            content: "";
            left: 0;
            position: absolute;
            top: 0;
          }
          p.info:before {
            background: #0066CC;
            border-radius: 16px;
            color: #fff;
            content: "i";
            font: bold 16px/24px serif;
            height: 24px;
            left: 0px;
            text-align: center;
            top: 4px;
            width: 24px;
          }

          @media (min-width: 768px) {
            body {
              margin: 6em;
            }
          }
        </style>
      </head>
      <body>
        <div>
          <h1>Sorry - Nothing to see here!</h1>
        </div>
      </body>
    </html>