# Example of ingresscontroller running on the infra nodes
# But exposes on different hostnetwork ports
# A separate user provided load balancer could load balance on those ports

apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: second-controller
  namespace: openshift-ingress-operator
spec:
  replicas: 2
  routeSelector:
    matchLabels:
      type: custom-second-domain
  domain: "second.os2.ticq.org"

  httpErrorCodePages:
    name: custom-error-code-pages

  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""  
    
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved

  endpointPublishingStrategy:
    type: HostNetwork
    hostNetwork:
      httpPort: 180
      httpsPort: 1443
      statsPort: 11936

  httpHeaders:
    actions:
      response:
      - name: Server
        action:
          type: Set
          set:
            value: WebserverX
    
  # access logging
  logging:
    access:
      destination:
        type: Container