{{- $namespaces := (include "tenants.namespaces" .) | fromYamlArray -}}
{{- range $ns := $namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "less-safe-sa"
  namespace: "{{ $ns.namespaceName }}"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "less-safe-sa-{{ $ns.namespaceName }}"
subjects:
  - kind: ServiceAccount
    name: "less-safe-sa"
    namespace: "{{ $ns.namespaceName }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: less-safe-sa
{{- end }}