{{- $namespaces := (include "tenants.namespaces" .) | fromYamlArray -}}
{{- range $ns := $namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "less-safe-sa"
  namespace: "{{ $ns.namespaceName }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: less-safe-sa
  namespace: "{{ $ns.namespaceName }}"
rules:
- apiGroups:
  - "security.openshift.io"
  resources:
  - "SecurityContextConstraints"
  verbs:
  - "use"
  resourceNames:
  - "nonroot-v2"
  - "restricted-v2"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: less-safe-sa
  namespace: "{{ $ns.namespaceName }}"
subjects:
  - kind: ServiceAccount
    name: "less-safe-sa"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: less-safe-sa
{{- end }}