{{- $namespaces := (include "tenants.namespaces" .) | fromYamlArray -}}
{{- range $ns := $namespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-same-namespace
  namespace: "{{ $ns.namespaceName }}"
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-from-openshift-ingress
#   namespace: "{{ $ns.namespaceName }}"
# spec:
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           network.openshift.io/policy-group: ingress
#   podSelector: {}
#   policyTypes:
#   - Ingress
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-from-openshift-monitoring
#   namespace: "{{ $ns.namespaceName }}"
# spec:
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           network.openshift.io/policy-group: monitoring
#   podSelector: {}
#   policyTypes:
#   - Ingress
{{- end }}
