---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  audit:
    # CIS Benchmark
    # profile: "Default" # For CIS this should be: WriteRequestBodies
    profile: "WriteRequestBodies"

  encryption:
    type: "aesgcm"
  
  # CIS benchmark
  tlsSecurityProfile:
    type: Custom     
    custom: 
      ciphers:
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-CHACHA20-POLY1305
      - ECDHE-RSA-CHACHA20-POLY1305
      minTLSVersion: VersionTLS12
