{{- range $component := $.Values.clusterComponents }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ $component.name }}"
  namespace: second-gitops
  {{- if and (ne $.Values.disableFinalizers "yes") (ne ($component.disableFinalizers | default "no") "yes") }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  {{- end }}

  {{- if $component.syncWave }} 
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $component.syncWave }}"
  {{- end }}
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: cluster
  source:
    path: "cluster-components/{{ $component.name }}"
    repoURL: "{{ $.Values.gitRepo }}"
    targetRevision: "{{ $.Values.targetRevision }}"
    helm:
      valueFiles:
      - values.yaml
      - "clusters/{{ $.Values.clusterName }}.yaml"
      ignoreMissingValueFiles: true

  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - ServerSideApply=true
    - FailOnSharedResource=true
{{- end }}
