{{- range $operator := $.Values.operators }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ $operator.name }}"
  namespace: second-gitops
  {{- if and (ne $.Values.disableFinalizers "yes") (ne ($operator.disableFinalizers | default "no") "yes") }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  {{- end }}

  labels:
    gitops.ticq.dev/operator: "true"

  {{- if $operator.syncWave }} 
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $operator.syncWave | default "-2" }}"
  {{- end }}
spec:
  destination:
    namespace: "{{ $operator.namespace | default "default" }}"
    server: https://kubernetes.default.svc
  project: cluster
  source:
    path: "operators/{{ $operator.name }}"
    repoURL: "{{ $.Values.gitRepo }}"
    targetRevision: "{{ $.Values.targetRevision }}"
    helm:
      valueFiles:
      - values.yaml
      - "clusters/{{ $.Values.clusterName }}.yaml"
      ignoreMissingValueFiles: true

  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - ServerSideApply=true
    - FailOnSharedResource=true

    {{- if ne ($operator.namespace | default "default") "default" }}
    - CreateNamespace=true
    {{- end }}
{{- end }}
