
{{- $tenants := (include "clusters.get-tenants" .) | fromYamlArray }}
{{- range $tenant := $tenants }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ print $tenant.name "-tenant" }}"
  namespace: "{{ $.Values.gitopsNamespace }}"

  {{- if ne $.Values.disableFinalizers "yes" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  {{- end }}
spec:
  project: cluster
  sources:
  - repoURL: "{{ $.Values.gitRepo }}"
    targetRevision: "{{ $.Values.targetRevision }}"
    path: tenants/
    helm:
        valueFiles:
        {{- if eq $tenant.enableTenantNamespaceAutoProvisioning "true" }}
        - $values/namespaces.yaml
        {{- end }}
        - ../clusters/tenants/defaults.yaml
        - ../clusters/cluster-tenants/{{ $.Values.clusterName }}.yaml
        - ../clusters/tenants/{{ $.Values.clusterName }}/{{ $tenant.name }}.yaml
        parameters:
        - name: "disableAutoSync"
          value: "{{ $.Values.disableAutoSync }}"
        - name: "disableFinalizers"
          value: "{{ $.Values.disableFinalizers }}"
        - name: "overrideTenants"
          value: "{{ $.Values.overrideTenants }}"
        fileParameters:
        - name: resources
          value: ../tenant-resources.yaml
  {{- if eq $tenant.enableTenantNamespaceAutoProvisioning "true" }}
  - repoURL: "{{ $tenant.tenantProvisionedRepository }}"
    targetRevision: "{{ $tenant.tenantProvisionedBranch }}"
    ref: values
  {{- end }}

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "{{ $.Values.gitopsNamespace }}"
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - ServerSideApply=true
    - FailOnSharedResource=true
{{- end }}
