
{{- range $name, $tenant := $.Values.tenants }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ print $name "-tenant" }}"
  namespace: "{{ $.Values.gitopsNamespace }}"

  {{- if ne $.Values.disableFinalizers "yes" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  {{- end }}
spec:
  project: cluster
  sources:
  - repoURL: "{{ $.Values.gitRepo }}"
    targetRevision: "{{ $.Values.targetRevision }}"
    path: tenants/
    helm:
        valueFiles:
        {{- if eq $tenant.enableTenantNamespaceAutoProvisioning "true" }}
        - $tenants/namespaces.yaml
        {{- end }}

        # cluster stuff
        - $values/tenants/defaults.yaml
        - $values/tenants/resources.yaml
        - $values/tenants/{{ $.Values.clusterType }}/defaults.yaml
        - $values/tenants/{{ $.Values.clusterType }}/{{ $.Values.clusterInstance }}/defaults.yaml

        - $values/tenants/{{ $name }}.yaml
        - $values/tenants/{{ $.Values.clusterType }}/{{ $name }}.yaml
        - $values/tenants/{{ $.Values.clusterType }}/{{ $.Values.clusterInstance }}/{{ $name }}.yaml
        ignoreMissingValueFiles: true
        parameters:
        - name: "disableAutoSync"
          value: "{{ $.Values.disableAutoSync }}"
        - name: "disableFinalizers"
          value: "{{ $.Values.disableFinalizers }}"
        - name: "overrideTenants"
          value: "{{ $.Values.overrideTenants }}"
  {{- if eq $tenant.enableTenantNamespaceAutoProvisioning "true" }}
  - repoURL: "{{ $tenant.tenantProvisionedRepository }}"
    targetRevision: "{{ $tenant.tenantProvisionedBranch }}"
    ref: tenants
  {{- end }}
  - repoURL: https://github.com/GijsvanDulmen/openshift-gitops-config
    targetRevision: "{{ $.Values.targetRevision }}"
    ref: values

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "{{ $.Values.gitopsNamespace }}"
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - ServerSideApply=true
    - FailOnSharedResource=true
{{- end }}
