operators-installer:

  operators:
    - channel: stable
      installPlanApproval: "Manual"
      name: servicemeshoperator3
      sourceNamespace: openshift-marketplace
      source: redhat-operators

      csv: servicemeshoperator3.v3.0.2
      namespace: service-mesh
      automaticIntermediateManualUpgrades: true

  operatorGroups:
  - name: service-mesh
    createNamespace: true
    targetOwnNamespace: false
