---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-cleaner
  namespace: central-config
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sandbox-cleaner
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sandbox-cleaner
subjects:
  - kind: ServiceAccount
    name: sandbox-cleaner
    namespace: central-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sandbox-cleaner
