---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-cleaner
  namespace: central-config
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sandbox-cleaner
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sandbox-cleaner
subjects:
  - kind: ServiceAccount
    name: sandbox-cleaner
    namespace: central-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sandbox-cleaner
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sandbox-cleaner
  namespace: central-config
spec:
  schedule: "0 0 * * 0" # every sunday
  jobTemplate:
    spec:
      template:
        metadata:
          name: sandbox-cleaner
        spec:
          serviceAccountName: sandbox-cleaner
          containers:
          - name: tester
            image: bitnami/kubectl
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 10m
                memory: 30Mi
            command:
            - "bin/bash"
            - "-c"
            - "kubectl delete ns -l gitops.ticq.dev\/user-sandbox=true"
          restartPolicy: Never