---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: UserConfig
metadata:
  name: user-sandbox
spec:
  providerName: githubidp
  templates:
  - excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas
    objectTemplate: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: {{`{{ lower .Name }}`}}-sandbox
        labels:
          gitops.ticq.dev/user-sandbox: "true"
        annotations:
          gitops.ticq.dev/user-sandbox: "true"
  - excludedPaths:	
        - .metadata	
        - .status	
        - .spec.replicas
    objectTemplate: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: {{`{{ lower .Name }}`}}-sandbox
        namespace: {{`{{ lower .Name }}`}}-sandbox
      subjects:
        - kind: User
          name: {{`{{ .Name }}`}}
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: edit
        apiGroup: rbac.authorization.k8s.io

