external-dns:
  provider: 
    name: cloudflare
    webhook:
      securityContext:
        fsGroup: 1000710000

  env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey
  interval: 2m
  sources:
  - service
  - openshift-route

  podSecurityContext:
    runAsNonRoot: true
    fsGroup: 1000710000
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000710000
    runAsGroup: 1000710000
    capabilities:
      drop: ["ALL"]
    
  extraArgs:
  # cloud flare specifics
  - --cloudflare-dns-records-per-page=5000
  - --cloudflare-proxied
  - --dyn-min-ttl=60 # cloud flare does not support lower

  # ingress VIP
  - --domain-filter=ticq.org
  - --default-targets=192.168.1.101
  # - --zone-id-filter=????