external-dns:
  provider: 
    name: cloudflare

  env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey
  interval: 2m
  sources:
  - service
  - openshift-route
  - gateway-httproute
  # - gateway-tlsroute
  # - gateway-tcproute
  # - gateway-udproute

  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop: ["ALL"]
    
  extraArgs:
  # cloud flare specifics
  - --cloudflare-dns-records-per-page=5000
  # - --cloudflare-proxied
  - --dyn-min-ttl=60 # cloud flare does not support lower

  # ingress VIP
  - --domain-filter=ticq.org
  # - --default-targets=192.168.2.100

  # only on our custom router
  # - --source=gateway-httproute
  # - --source=gateway-tlsroute
  # - --source=gateway-tcproute
  # - --source=gateway-udproute

  - --openshift-router-name=custom
  # - --zone-id-filter=????