---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  {{- $appProjectName := print "tenant-" $.Values.name }}
  name: "{{ $appProjectName }}"
  namespace: tenant-gitops
spec:
  sourceRepos:
  - '*'
  destinations:
  {{- range $ns := $.Values.namespaces }}
  - namespace: "{{ $.Values.name }}-{{ $ns.name }}"
    server: https://kubernetes.default.svc
  {{- end }}
# no cluster resource whitelist allowed
#   clusterResourceWhitelist:
#   - group: '*'
#     kind: '*'

