---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  {{- $appProjectName := print "tenant-" $.Values.name }}
  name: "{{ $appProjectName }}"
  namespace: tenant-gitops
spec:
  # make this less obviously!
  clusterResourceWhitelist:
  - group: ''
    kind: ''  

  namespaceResourceWhitelist:
  {{- range $resource := $.Values.tenantResources }}
  {{- if $resource.argoKinds }}
  {{- range $apiGroup := $resource.apiGroups }}
  {{- range $argoKind := $resource.argoKinds }}
  - group: "{{ $apiGroup }}"
    kind: "{{ $argoKind }}"
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  
  # allow all because...
  sourceRepos:
  - '*'
  destinations:
  {{- $namespaces := (include "tenants.namespaces" .) | fromYamlArray -}}
  {{- range $ns := $namespaces }}
  - name: "{{ $ns.namespaceName }}"
    namespace: "{{ $ns.namespaceName }}"
    server: https://kubernetes.default.svc
  {{- end }}
  roles:
    - description: Group for tenant
      groups:
        - tenant-{{ $.Values.name }}
      name: tenant-{{ $.Values.name }}
      policies:
        # we use applicationsets!
        # - p, proj:{{ $appProjectName }}:tenant-{{ $.Values.name }}, applications, create, {{ $appProjectName }}/*, allow
        # - p, proj:{{ $appProjectName }}:tenant-{{ $.Values.name }}, applications, update, {{ $appProjectName }}/*, allow
        # - p, proj:{{ $appProjectName }}:tenant-{{ $.Values.name }}, applications, delete, {{ $appProjectName }}/*, allow

        - p, proj:{{ $appProjectName }}:tenant-{{ $.Values.name }}, applications, get, {{ $appProjectName }}/*, allow
        - p, proj:{{ $appProjectName }}:tenant-{{ $.Values.name }}, applications, sync, {{ $appProjectName }}/*, allow
        - p, proj:{{ $appProjectName }}:tenant-{{ $.Values.name }}, applications, override, {{ $appProjectName }}/*, allow
        
        # extra added
        - p, proj:{{ $appProjectName }}:tenant-{{ $.Values.name }}, logs, get, {{ $appProjectName }}/*, allow
        - p, proj:{{ $appProjectName }}:tenant-{{ $.Values.name }}, repositories, get, {{ $appProjectName }}/*, allow

