---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  {{- $appProjectName := print "tenant-" $.Values.name }}
  name: "{{ $appProjectName }}"
  namespace: tenant-gitops
spec:
  sourceRepos:
  - '*'
  destinations:
  {{- $namespaces := (include "tenants.namespaces" .) | fromYamlArray -}}
  {{- range $ns := $namespaces }}
  - namespace: "{{ $ns.namespaceName }}"
    server: https://kubernetes.default.svc
  {{- end }}
# no cluster resource whitelist allowed
#   clusterResourceWhitelist:
#   - group: '*'
#     kind: '*'

