{{- range $ns := $.Values.namespaces }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: "{{ $.Values.name }}-{{ $ns.name }}"
spec:
  limits:
    - type: Container
      {{- $containerLimits := merge ($ns.containerLimits | default dict) $.Values.containerLimits }}
      {{- nindent 6 ($containerLimits | toYaml) }}
    - type: PersistentVolumeClaim
      {{- $persistentVolumeClaimLimits := merge ($ns.persistentVolumeClaimLimits | default dict) $.Values.persistentVolumeClaimLimits }}
      {{- nindent 6 ($persistentVolumeClaimLimits | toYaml) }}

    - type: Pod
      {{- $podLimits := merge ($ns.podLimits | default dict) $.Values.podLimits }}
      {{- nindent 6 ($podLimits | toYaml) }}      

{{- end }}