{{- $namespaces := (include "tenants.namespaces" .) | fromYamlArray -}}
{{- range $ns := $namespaces }}
{{- if eq $.Values.quotaType "namespace" }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: "{{ $ns.namespaceName }}"
spec:
  hard:
    {{- $resourceQuota := merge $.Values.namespaceResourceQuota $.Values.defaultOverallResourceQuota }}
    {{- $resourceQuota = merge ($ns.resourceQuota | default dict) $resourceQuota }}
    {{- nindent 4 ($resourceQuota | toYaml) }}

{{- end }}
{{- end }}