{{- range $ns := $.Values.namespaces }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "tenant-edit-{{ $.Values.name }}"
  name: "{{ $.Values.name }}-{{ $ns.name }}"
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: "tenant-{{ $.Values.name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
{{- end }}