---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $.Values.gitopsNamespace }}-argocd-application-controller-allow-list"
subjects:
  - kind: ServiceAccount
    name: "{{ $.Values.gitopsNamespace }}-argocd-application-controller"
    namespace: "{{ $.Values.gitopsNamespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
