apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resources
  namespace: "{{ $.Values.gitopsNamespace }}"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: cluster
  sources:
    - path: clusters
      repoURL: https://github.com/GijsvanDulmen/openshift-gitops-setup
      targetRevision: HEAD
      helm:
        valueFiles:
        - $values/config/values.yaml
        - $values/config/{{ $.Values.clusterType }}/values.yaml
        - $values/config/{{ $.Values.clusterType }}/{{ $.Values.clusterInstance }}/values.yaml
        - $values/config/tenant-resources.yaml
        parameters:
        - name: "disableAutoSync"
          value: "{{ $.Values.disableAutoSync }}"
        - name: appRevision
          value: $ARGOCD_APP_REVISION
        - name: targetRevision
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
        - name: gitRepo
          value: $ARGOCD_APP_SOURCE_REPO_URL
        - name: gitopsNamespace
          value: "{{ $.Values.gitopsNamespace }}"
        - name: "disableFinalizers"
          value: "no"
        - name: "overrideTenants"
          value: "no"
    - repoURL: https://github.com/GijsvanDulmen/openshift-gitops-config
      targetRevision: HEAD
      ref: values

  # test this
  ignoreDifferences:
  - group: "apps"
    kind: "Deployment"
    jsonPointers:
    - /spec/replicas
  - group: ""
    kind: "Service"
    jsonPointers:
    - /spec/externalIPs
  - group: ""
    kind: Node
    jsonPointers:
    - /spec/taints

  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - PrunePropagationPolicy=foreground
    - ServerSideApply=true
    - FailOnSharedResource=true
