operators-installer:

  installPlanApproverAndVerifyJobsImage: registry.redhat.io/openshift4/ose-cli:v4.15

  operators:
    - channel: stable
      installPlanApproval: "Manual"
      name: cluster-kube-descheduler-operator
      sourceNamespace: openshift-marketplace
      source: redhat-operators
      csv: clusterkubedescheduleroperator.v5.0.1
      namespace: openshift-kube-descheduler-operator
      automaticIntermediateManualUpgrades: true

  operatorGroups:
  - name: openshift-kube-descheduler-operator
    createNamespace: true
    targetOwnNamespace: false
