# usually we add this to the machineset for node labeling
# for now we test this way
---
apiVersion: v1
kind: Node
metadata:
  name: worker-2
  labels:
    # tenant: team-backend-apps
    topology.kubernetes.io/zone: "deventer-01"

    # make egress ips possible
    k8s.ovn.org/egress-assignable: ""
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
#   taints:
#   - effect: NoSchedule
#     key: team-backend-apps
#     value: ""
---
apiVersion: v1
kind: Node
metadata:
  name: worker-1
  labels:
    topology.kubernetes.io/zone: "deventer-02"

    # make egress ips possible
    k8s.ovn.org/egress-assignable: ""
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  taints: []