# usually we add this to the machineset for node labeling
# for now we test this way
---
apiVersion: v1
kind: Node
metadata:
  name: worker-2
  labels:
    tenant: team-backend-apps
  annotations:
    argocd.argoproj.io/sync-options: "Delete=false"
spec:
  taints:
  - effect: NoSchedule
    key: team-backend-apps
    value: ""