---
apiVersion: operator.openshift.io/v1
kind: DNS
metadata:
  name: default
spec:
  servers:

  # just a small example from docs
  - name: foo-server
    zones:
      - foo.com
    forwardPlugin:
      policy: Random
      upstreams:
        - 1.1.1.1