operators-installer:

  installPlanApproverAndVerifyJobsImage: registry.redhat.io/openshift4/ose-cli:v4.15

  operators:
    - channel: stable
      installPlanApproval: "Manual"
      name: vertical-pod-autoscaler
      sourceNamespace: openshift-marketplace
      source: redhat-operators
      csv: verticalpodautoscaler.v4.16.0-202408201708
      namespace: openshift-vertical-pod-autoscaler
      automaticIntermediateManualUpgrades: true

  operatorGroups:
  - name: openshift-vertical-pod-autoscaler
    createNamespace: true
    targetOwnNamespace: true
