{{- $namespaces := (include "tenants.namespaces" .) | fromYamlArray -}}
{{- range $ns := $namespaces }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-ticq-org
  namespace: "{{ $ns.namespaceName }}"
spec:
  commonName: cloud.ticq.org
  dnsNames:
    - "cloud.ticq.org"
  secretName: cloud-ticq-org
  isCA: false
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-cluster-issuer-production
    kind: ClusterIssuer
{{- end }}
{{- end }}