---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer-production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "gijs@vandulmen.net"
    privateKeySecretRef:
      name: acme-account-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: apiKey
              name: cloudflare-api-key