{{- $namespaces := (include "tenants.namespaces" .) | fromYamlArray -}}
{{- range $ns := $namespaces }}
{{- if ($ns.gitops | default dict).repository }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "tenants-{{ $ns.namespaceName }}"
  namespace: "tenant-gitops"

  # needed for applicationset
  {{- if ne $.Values.disableFinalizers "yes" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  {{- end }}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  {{- if eq $.Values.overrideTenants "yes" }}
  # ability to fast-forward and/or change targetRevisions
  # and ability to shut down sync policy
  ignoreApplicationDifferences:
    - jsonPointers:
      - /spec/source/targetRevision
    - jsonPointers:
      - /spec/syncPolicy
  {{- end }}

  generators:
  - git:
      repoURL: "{{ $ns.gitops.repository }}"
      revision: "{{ $ns.gitops.revision | default "HEAD" }}"
      files:
      - path: "*/namespaces/{{ $ns.name }}.yaml"
  template:
    metadata:
      name: "{{ $ns.namespaceName }}-{{ `{{ index .path.segments 0 }}` }}"

      # will delete everything on the application of a tenant
      {{- if ne $.Values.disableFinalizers "yes" }}
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      {{- end }}
    spec:
      project: {{ print "tenant-" $.Values.name }}
      source:
        repoURL: "{{ $ns.gitops.repository }}"
        targetRevision: "{{ $ns.gitops.revision | default "HEAD" }}"
        path: "{{ `{{ index .path.segments 0 }}` }}/"
        helm:
            valueFiles:
            - values.yaml
            - "namespaces/{{ $ns.name }}.yaml"
            - "images/{{ $ns.name }}.yaml"
            ignoreMissingValueFiles: true
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: {{ $ns.namespaceName }}
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - PrunePropagationPolicy=foreground
        - ServerSideApply=true
        - FailOnSharedResource=true

{{- end }}
{{- end }}