---
apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster
  namespace: openshift-kube-descheduler-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  mode: Automatic
  deschedulingIntervalSeconds: 20
  profiles:
  - SoftTopologyAndDuplicates
  # - LifecycleAndUtilization
  profileCustomizations:
    podLifetime: 1m
    # Sets the included/excluded namespaces for all strategies
    # (included namespaces are not allowed to include protected
    # namespaces which consist of kube-system, hypershift and all openshift- prefixed namespaces)
    namespaces:
      excluded: []
      # included:
      # Unfortunately descheduler can not use matchLabels
      # Or something similar
      # We could opt for not using a whitelist and use a blacklist
      # {{- range $tenant := $tenants }}
      # {{- range $ns := $tenant.namespaces }}
      # - "{{ $tenant.name }}-{{ $ns.name }}"
      # {{- end }}
      # {{- end }}