apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: istio-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-from-tenants
#   namespace: "istio-ingress"
# spec:
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           gitops.ticq.dev/ingress-type: istio
#   podSelector: {}
#   policyTypes:
#   - Ingress
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: allow-from-istio-system
#   namespace: "istio-ingress"
# spec:
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: istio-system
#   podSelector: {}
#   policyTypes:
#   - Ingress