apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: istio-ingress
spec:
  podSelector: {}
  policyTypes:
#   - Egress
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-the-world-but-not-cluster
  namespace: istio-ingress
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          gitops.ticq.dev/type: "tenant"
  - from:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
            # clusterNetwork (oc get networks.config.openshift.io cluster -o yaml)
            - 10.128.0.0/14
            # serviceNetwork (oc get networks.config.openshift.io cluster -o yaml)
            - 172.30.0.0/16
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-istio-system
  namespace: istio-ingress
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
  podSelector: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-tenants
  namespace: istio-ingress
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          gitops.ticq.dev/ingress-type: istio
  podSelector: {}
  policyTypes:
  - Egress