apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: "{{ $.Values.gitopsNamespace }}"
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  {{- if eq $.Values.disableAutoSync "yes" }}
  syncWindows:
  - kind: deny
    schedule: '5 0 * * *'
    duration: 24h
    manualSync: true
  {{- end }}