operators-installer:

  operators:
    - channel: alpha
      installPlanApproval: "Manual"
      name: namespace-configuration-operator
      sourceNamespace: openshift-marketplace
      source: community-operators
      csv: namespace-configuration-operator.v1.2.6
      namespace: namespace-configuration-operator
      automaticIntermediateManualUpgrades: true

  operatorGroups:
  - name: namespace-configuration-operator
    createNamespace: true
    targetOwnNamespace: false
