---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-less-secure-scc 
  namespace: minio-backup
rules:
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints 
  verbs:
  - use