
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  # apps.os2.ticq.org
  name: apps-os2-ticq-org
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  commonName: apps.os2.ticq.org
  dnsNames:
    - "apps.os2.ticq.org" 
    - "*.apps.os2.ticq.org"
  secretName: apps-os2-ticq-org
  isCA: false
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-cluster-issuer-production
    kind: ClusterIssuer
