operators-installer:

  operators:
    - channel: stable
      installPlanApproval: "Manual"
      name: compliance-operator
      sourceNamespace: openshift-marketplace
      source: redhat-operators
      csv: compliance-operator.v1.6.2
      namespace: openshift-compliance
      automaticIntermediateManualUpgrades: true

  operatorGroups:
  - name: openshift-compliance
    createNamespace: true
    targetOwnNamespace: false
