operators-installer:

  installPlanApproverAndVerifyJobsImage: registry.redhat.io/openshift4/ose-cli:v4.15

  operators:
    - channel: alpha
      installPlanApproval: "Manual"
      name: keepalived-operator
      sourceNamespace: openshift-marketplace
      source: community-operators
      csv: keepalived-operator.v1.5.4
      namespace: keepalived-operator
      automaticIntermediateManualUpgrades: true

  operatorGroups:
  - name: keepalived-operator
    createNamespace: true
    targetOwnNamespace: false
