### REALLY EVIL HACK! ###
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-controller-admin
  namespace: kargo-team-backend
subjects:
  - kind: ServiceAccount
    name: kargo-controller
    namespace: kargo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
