apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-ingress
  annotations:
    keepalived-operator.redhat-cop.io/keepalivedgroup: keepalived-operator/keepalivedgroup-router
    external-dns.alpha.kubernetes.io/target: "{{ $.Values.istioIngressIp }}"
    external-dns.alpha.kubernetes.io/hostname: "{{ $.Values.ingressHostname }}"
spec:
  gatewayClassName: istio

  addresses:
  - value: "{{ $.Values.istioIngressIp }}"
    type: IPAddress

  listeners:
  - name: default
    port: 80
    protocol: HTTP

    hostname: "{{ $.Values.ingressHostname }}"

    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gitops.ticq.dev/ingress-type: istio

  - name: https
    port: 443
    protocol: HTTPS

    hostname: "{{ $.Values.ingressHostname }}"

    tls:
      mode: Terminate # If protocol is `TLS`, `Passthrough` is a possible mode
      certificateRefs:
      - kind: Secret
        group: ""
        name: cloud-ticq-org

    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            gitops.ticq.dev/ingress-type: istio
