gitopsNamespace: "second-gitops"
disableAutoSync: "no"

operators-installer:

  operators:
    - channel: latest
      installPlanApproval: "Manual"
      name: openshift-gitops-operator
      sourceNamespace: openshift-marketplace
      
      source: redhat-operators # use this for non disconnected
      # source: "cs-redhat-operator-index-v4-18" # use this for disconnected

      csv: openshift-gitops-operator.v1.16.1
      namespace: openshift-gitops-operator
      automaticIntermediateManualUpgrades: true
      config:
        env:
        - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
          value: "openshift-gitops, second-gitops, tenant-gitops"
        - name: DISABLE_DEFAULT_ARGOCD_CONSOLELINK
          value: "false"

        # disable this!
        - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
          value: "true"

        # if overriden for local argocds
        - name: CONTROLLER_CLUSTER_ROLE
          value: custom-controller-role
        - name: SERVER_CLUSTER_ROLE
          value: custom-server-role

  operatorGroups:
  - name: openshift-gitops-operator
    createNamespace: true
    targetOwnNamespace: false

