operators-installer:

  operators:
    - channel: stable-4.19
      installPlanApproval: "Manual"
      name: lvms-operator
      sourceNamespace: openshift-marketplace
      source: redhat-operators
      csv: lvms-operator.v4.19.0
      namespace: openshift-storage
      automaticIntermediateManualUpgrades: true

  operatorGroups:
  - name: openshift-storage
    createNamespace: false
    targetOwnNamespace: true
