kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tenant-edit
rules:
{{- $resources := (include "clusters.get-tenant-resources" .) | fromYamlArray }}
{{- range $resource := $resources }}
- verbs:
  {{- range $verb := $resource.verbs }}
  - "{{ $verb }}"
  {{- end }}
  apiGroups:
  {{- range $apiGroup := $resource.apiGroups }}
  - "{{ $apiGroup }}"
  {{- end }}
  resources:
  {{- range $resource := $resource.resources }}
  - "{{ $resource }}"
  {{- end }}
{{- end }}
